### ISSUE TITLE
cmd_logo.png overtreedt huisstijl CMD

### ISSUE THREAD

**Issue by rijkvanzanten** [CMDA/FED1#11]
Het 'logo' van CMD wat geleverd wordt in het pakket voor Front-End Development is in strijd met de huisstijl-regels van CMD Amsterdam. Zoals te lezen is op bladzijde 9 van [de stijlgids](https://moodle.cmd.hva.nl/pluginfile.php/5040/mod_page/content/1/CMD_brand_guide%20def.pdf) worden de letters C, M en D ingezet als iconen tussen de andere iconen, en niet gebruikt als logo.

![schermafbeelding 2015-09-27 om 20 28 21](https://cloud.githubusercontent.com/assets/9141017/10124485/67f966c2-6556-11e5-8c01-a6e08744f0f6.png)

**Comment by KoopReynders** [comment]
Ha ha.

**Comment by KoopReynders** [comment]
Die heb ik gemaakt/gebruikt voor dit filmpje: 
https://m.youtube.com/watch?v=fB28wli-AVA

Goede reden hè?

**Comment by TimArisz** [comment]
Dat is een horizontale totem dat zie je toch zelf ook wel Rijk...

**Comment by RijkvanZanten** [comment]
![cmd](https://cloud.githubusercontent.com/assets/9141017/11269468/5acbac82-8eb7-11e5-9026-0c76ea515278.png)

**Comment by wooorm** [comment]
🤷‍♂️
